#!/bin/sh
# chkconfig: 345 90 20
# description: Perforce

### BEGIN INIT INFO
# Provides: perforce
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop service perforce
# Description: perforce
### END INIT INFO

. /lib/lsb/init-functions

P4ROOT=/var/local/perforce
P4JOURNAL=/var/local/perforce/journal
P4LOG=/var/local/perforce/logs/p4err
P4PORT=1666
P4USER=jpostma
P4PASSWD=password

case "$1" in
start)
p4d -r $P4ROOT -J $P4JOURNAL -L $P4LOG -p $P4PORT -d
;;
stop)
p4 -p$P4PORT -u$P4USER -P$P4PASSWD admin stop
;;
restart)
p4 -p$P4PORT -u$P4USER -P$P4PASSWD admin stop
p4d -r $P4ROOT -J $P4JOURNAL -L $P4LOG -p $P4PORT -d
;;
*)
printf "Usage: %s {start|stop|restart}\n" "$0"
exit 1
esac

exit 0
